version: '2'
services:
  es:
    build:
      context: .
      dockerfile: Dockerfile_es
    volumes:
      - /mnt/sda1/data/es-training/es:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    links:
      - es2
  es2:
    build:
      context: .
      dockerfile: Dockerfile_es2
    volumes:
      - /mnt/sda1/data/es-training/es2:/usr/share/elasticsearch/data
  #  ports:
  #    - 9200:9200
  #    - 9300:9300
