version: '2'
services:
  es:
    build: .
    volumes:
      - /mnt/sda1/data/es-training/es:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    links:
      - logstash
      - kibana
      - es2
    environment:
      - ES_HOST=es
      - OTHER_HOST=es2
  es2:
    build: .
    volumes:
      - /mnt/sda1/data/es-training/es2:/usr/share/elasticsearch/data
    environment:
      - ES_HOST=es2
      - OTHER_HOST=es
  kibana:
      image: kibana
      ports:
        - 5601:5601
      environment:
        - ELASTICSEARCH_URL=http://es:9200
  logstash:
      image: logstash
      volumes:
        - .:/var/logstash/
      command: logstash -f /var/logstash/logstash.conf
