version: '2'
services:
  es:
    build: .
    ports:
      - "9200:9200"
      - "9300:9300"
    links:
      - es2
      - es3
    environment:
      - ES_HOST=es
      - OTHER_HOST=es2,es3
  es2:
    build: .
    environment:
      - ES_HOST=es2
      - OTHER_HOST=es,es3
  es3:
    build: .
    environment:
      - ES_HOST=es3
      - OTHER_HOST=es,es2
